from __future__ import annotations
from typing import Generic, Iterator, TypeVar


_T = TypeVar('_T')


class SortedSet(Generic[_T]):
    def add(self, t: _T): ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[_T]: ...
    def __getitem__(self: SortedSet, s: slice) -> SortedSet: ...
